// lex.yy.cpp generated by reflex 6.0.0 from automata.l

#define REFLEX_VERSION "6.0.0"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#define REFLEX_OPTION_graphs_file         "Automata.gv"
#define REFLEX_OPTION_lex                 lex
#define REFLEX_OPTION_lexer               Lexer
#define REFLEX_OPTION_outfile             "lex.yy.cpp"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  REGEX MATCHER                                                             //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/matcher.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  ABSTRACT LEXER CLASS                                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/abslexer.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS                                                               //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

class Lexer : public reflex::AbstractLexer<reflex::Matcher> {
 public:
  typedef reflex::AbstractLexer<reflex::Matcher> AbstractBaseLexer;
  Lexer(
      // a persistent source of input, empty by default
      const reflex::Input& input = reflex::Input(),
      // optional output stream, std::cout by default
      std::ostream& os = std::cout)
    :
      AbstractBaseLexer(input, os)
  {
  }
  static const int INITIAL = 0;
  // the lexer function defined by SECTION 2
  virtual int lex(void);
  // lexer functions accepting new input to scan
  int lex(const reflex::Input& input)
  {
    in(input);
    return lex();
  }
  int lex(const reflex::Input& input, std::ostream *os)
  {
    in(input);
    if (os)
      out(*os);
    return lex();
  }
};

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 2: rules                                                          //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

int Lexer::lex(void)
{
  static const char *REGEX_INITIAL = "(?m)(-?[0-9]+)|([A-Z_a-z][0-9A-Z_a-z]*)|((?:\\Q//\\E).*)|((?:\\Q+\\E))|((?:\\Q-\\E))|((?:\\Q*\\E))|((?:\\Q/\\E))|((?:\\Q%\\E))|((?:\\Q==\\E))|((?:\\Q=\\E))|((?:\\Q!=\\E))|((?:\\Q<\\E))|((?:\\Q>\\E))|((?:\\Q<=\\E))|((?:\\Q>=\\E))|((?:\\Q&&\\E))|((?:\\Q||\\E))|((?:\\Q!\\E))|((?:\\Q;\\E))|((?:\\Q,\\E))|((?:\\Q(\\E))|((?:\\Q)\\E))|((?:\\Q{\\E))|((?:\\Q}\\E))";
  static const reflex::Pattern PATTERN_INITIAL(REGEX_INITIAL);
  if (!has_matcher())
  {
    matcher(new Matcher(PATTERN_INITIAL, stdinit(), this));
  }
  while (true)
  {
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
              return int();
            }
            else
            {
              out().put(matcher().input());
            }
            break;
          case 1: // rule automata.l:2: -?[0-9]+ :
#line 2 "automata.l"
            break;
          case 2: // rule automata.l:3: [a-zA-Z_][a-zA-Z_0-9]* :
#line 3 "automata.l"
            break;
          case 3: // rule automata.l:4: "//".* :
#line 4 "automata.l"
            break;
          case 4: // rule automata.l:5: "+" :
#line 5 "automata.l"
            break;
          case 5: // rule automata.l:6: "-" :
#line 6 "automata.l"
            break;
          case 6: // rule automata.l:7: "*" :
#line 7 "automata.l"
            break;
          case 7: // rule automata.l:8: "/" :
#line 8 "automata.l"
            break;
          case 8: // rule automata.l:9: "%" :
#line 9 "automata.l"
            break;
          case 9: // rule automata.l:10: "==" :
#line 10 "automata.l"
            break;
          case 10: // rule automata.l:11: "=" :
#line 11 "automata.l"
            break;
          case 11: // rule automata.l:12: "!=" :
#line 12 "automata.l"
            break;
          case 12: // rule automata.l:13: "<" :
#line 13 "automata.l"
            break;
          case 13: // rule automata.l:14: ">" :
#line 14 "automata.l"
            break;
          case 14: // rule automata.l:15: "<=" :
#line 15 "automata.l"
            break;
          case 15: // rule automata.l:16: ">=" :
#line 16 "automata.l"
            break;
          case 16: // rule automata.l:17: "&&" :
#line 17 "automata.l"
            break;
          case 17: // rule automata.l:18: "||" :
#line 18 "automata.l"
            break;
          case 18: // rule automata.l:19: "!" :
#line 19 "automata.l"
            break;
          case 19: // rule automata.l:20: ";" :
#line 20 "automata.l"
            break;
          case 20: // rule automata.l:21: "," :
#line 21 "automata.l"
            break;
          case 21: // rule automata.l:22: "(" :
#line 22 "automata.l"
            break;
          case 22: // rule automata.l:23: ")" :
#line 23 "automata.l"
            break;
          case 23: // rule automata.l:24: "{" :
#line 24 "automata.l"
            break;
          case 24: // rule automata.l:25: "}" :
#line 25 "automata.l"
            break;
        }
  }
}
